config/routes.rb
Rails.application.routes.draw do
  root to: "formulaires#index"
  resources :candidats
  resources :options
  resources :questions
  resources :formulaires
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidat.rb
class Candidat < ApplicationRecord
  belongs_to :formulaire
  serialize :responses , Hash
end

app/controllers/candidats_controller.rb
class CandidatsController < ApplicationController
  before_action :set_candidat, only: [:show, :edit, :update, :destroy]

  # GET /candidats
  # GET /candidats.json
  def index
    @candidats = Candidat.all
  end

  # GET /candidats/1
  # GET /candidats/1.json
  def show
  end

  # GET /candidats/new
  def new
    @candidat = Candidat.new(formulaire_id: params[:formulaire])
  end

  # GET /candidats/1/edit
  def edit
  end

  # POST /candidats
  # POST /candidats.json
  def create
    @candidat = Candidat.new(candidat_params)

    respond_to do |format|
      if @candidat.save
        format.html { redirect_to @candidat, notice: 'Candidat was successfully created.' }
        format.json { render :show, status: :created, location: @candidat }
      else
        format.html { render :new }
        format.json { render json: @candidat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidats/1
  # PATCH/PUT /candidats/1.json
  def update
    respond_to do |format|
      if @candidat.update(candidat_params)
        format.html { redirect_to @candidat, notice: 'Candidat was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidat }
      else
        format.html { render :edit }
        format.json { render json: @candidat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidats/1
  # DELETE /candidats/1.json
  def destroy
    @candidat.destroy
    respond_to do |format|
      format.html { redirect_to candidats_url, notice: 'Candidat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidat
      @candidat = Candidat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidat_params
      params.require(:candidat).permit(:formulaire_id , responses: {})
    end
end

app/helpers/candidats_helper.rb
module CandidatsHelper
end

app/views/candidats/_form.html.erb
<%= form_for @candidat do |f| %>
  <% if @candidat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidat.errors.count, "error") %> prohibited this candidat from being saved:</h2>

      <ul>
      <% @candidat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :formulaire_id%>

  <%= f.fields_for :responses , OpenStruct.new(@candidat.responses) do |builder| %>
    <% @candidat.formulaire.questions.each do |field| %>
      <%= render "candidats/fields/#{field.type_field}" , field: field , f: builder%>
    <%end%>
  <%end%>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidats/edit.html.erb
<h1>Editing Candidat</h1>

<%= render 'form', candidat: @candidat %>

<%= link_to 'Show', @candidat %> |
<%= link_to 'Back', candidats_path %>

app/views/candidats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidats</h1>

<table>
  <thead>
  </thead>

  <tbody>
    <% @candidats.each do |candidat| %>
      <tr>
        <td style="font-weight: bold;"> <%= candidat.formulaire.title %> </td>
        <td><%= candidat.responses.first[1] %></td>
        <td><%= link_to 'Show', candidat %></td>
        <td><%= link_to 'Edit', edit_candidat_path(candidat) %></td>
        <td><%= link_to 'Destroy', candidat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidat', formulaires_path %>

app/views/candidats/new.html.erb
<h1>New Candidat</h1>

<%= render 'form', candidat: @candidat %>

<%= link_to 'Back', candidats_path %>

app/views/candidats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Formulaire:</strong>
  <%= @candidat.formulaire.title %>
</p>

<p>
  <strong>Candidat: <%= @candidat.id%> </strong>
</p>


<% if @candidat.responses.present?%>
  <% @candidat.responses.each do |key , value|%>
      <p>
        <strong><%= key.humanize %>:</strong>
        <%= value %>
      </p>
  <%end%>
<%end%>



<%= link_to 'Edit', edit_candidat_path(@candidat) %> |
<%= link_to 'Back', candidats_path %>