config/routes.rb
Rails.application.routes.draw do
  root to: "formulaires#index"
  resources :candidats
  resources :options
  resources :questions
  resources :formulaires
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/formulaire.rb
class Formulaire < ApplicationRecord
    has_many :questions
    has_many :candidats
    accepts_nested_attributes_for :questions, allow_destroy: true , :reject_if => lambda { |d| d[:title].blank?}
end

app/controllers/formulaires_controller.rb
class FormulairesController < ApplicationController
  before_action :set_formulaire, only: [:show, :edit, :update, :destroy]

  # GET /formulaires
  # GET /formulaires.json
  def index
    @formulaires = Formulaire.all
  end

  # GET /formulaires/1
  # GET /formulaires/1.json
  def show
  end

  # GET /formulaires/new
  def new
    @formulaire = Formulaire.new
  end

  # GET /formulaires/1/edit
  def edit
  end

  # POST /formulaires
  # POST /formulaires.json
  def create
    @formulaire = Formulaire.new(formulaire_params)

    respond_to do |format|
      if @formulaire.save
        format.html { redirect_to @formulaire, notice: 'Formulaire was successfully created.' }
        format.json { render :show, status: :created, location: @formulaire }
      else
        format.html { render :new }
        format.json { render json: @formulaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formulaires/1
  # PATCH/PUT /formulaires/1.json
  def update
    respond_to do |format|
      if @formulaire.update(formulaire_params)
        format.html { redirect_to @formulaire, notice: 'Formulaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @formulaire }
      else
        format.html { render :edit }
        format.json { render json: @formulaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formulaires/1
  # DELETE /formulaires/1.json
  def destroy
    @formulaire.destroy
    respond_to do |format|
      format.html { redirect_to formulaires_url, notice: 'Formulaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulaire
      @formulaire = Formulaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formulaire_params
      params.require(:formulaire).permit(:title, :description , questions_attributes: {})
    end
end

app/helpers/formulaires_helper.rb
module FormulairesHelper
end

app/views/formulaires/_form.html.erb
<%= form_with(model: formulaire, local: true) do |f| %>
  <% if formulaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formulaire.errors.count, "error") %> prohibited this formulaire from being saved:</h2>

      <ul>
      <% formulaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <%= f.fields_for :questions do |builder|%>
    <%= render 'question_fields' , f: builder %>
  <% end %><br/>
  <%= link_to_add_fields "Add Question" , f, :questions%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formulaires/_option_fields.html.erb
<fieldset class= "option_field_set">
    <%= f.hidden_field :question_id%>
    <%= f.label :title  , "Option"%><br/>
    <%= f.text_field :title , placeholder: "Option..." %>
    <%= f.hidden_field :_destroy%>
    <%= link_to "Remove",  "#", class: "remove_fields remove_option"%>
</fieldset>

app/views/formulaires/_question_fields.html.erb
<fieldset>
    <div class="group">
    <%= f.select :type_field , Question::TYPE_FIELDS.collect{ |type_field| [type_field[:key] , type_field[:value]]}  , {include_blank: "choisir le type"} ,{ class: "choose_type" }%> 
    <%= f.hidden_field :formulaire_id%>
    <%= f.text_field :title ,placeholder: "Question..." , class: "text_elem"%><br/><br/>
    
    <%= f.hidden_field :_destroy%>
    <%= link_to "Remove Question",  "#", class: "remove_fields"%>
    </div>
    
    <%= f.fields_for :options  do |builder|%>
        <%= render 'option_fields' , f: builder%>
    <% end %><br/><br/>
    <span class="button_add_option" style="display: none;">
    <%= link_to_add_fields "Add Option" , f, :options%>
    </span>

</fieldset>

<script type="text/javascript">
    $(document).ready(function(){
        $(".choose_type").on("change", function(){
            if( $(this).val() === "select" || $(this).val() === "check_box"  || $(this).val() === "radio_button" ){
                $(this).closest('fieldset').find('.button_add_option').show();
            }else{
                $(this).closest('fieldset').find('.button_add_option').hide();
            }
        });
        
        $(".choose_type").each(function(){
            if( $(this).val() === "select" || $(this).val() === "check_box" || $(this).val() === "radio_button" ){
                $(this).closest('fieldset').find('.button_add_option').show();
            }
        });
    });
</script>

app/views/formulaires/edit.html.erb
<h1>Editing Formulaire</h1>

<%= render 'form', formulaire: @formulaire %>

<%= link_to 'Show', @formulaire %> |
<%= link_to 'Back', formulaires_path %>

app/views/formulaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formulaires</h1>

<table>
  <thead>
  </thead>

  <tbody>
    <% @formulaires.each do |formulaire| %>
      <tr>
        <td style="font-weight: bold;"><%= formulaire.title %></td>
        <!--<td><%#= formulaire.description %></td>-->
        <td><%= link_to 'Show', formulaire %></td>
        <td><%= link_to 'Edit', edit_formulaire_path(formulaire) %></td>
        <td><%= link_to 'Destroy', formulaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Candidater', new_candidat_path(formulaire: formulaire) , method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formulaire', new_formulaire_path %>

app/views/formulaires/new.html.erb
<h1>New Formulaire</h1>

<%= render 'form', formulaire: @formulaire %>

<%= link_to 'Back', formulaires_path %>

app/views/formulaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @formulaire.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @formulaire.description %>
</p>

<%= link_to 'Edit', edit_formulaire_path(@formulaire) %> |
<%= link_to 'Back', formulaires_path %>